accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from accounts.views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

app_name = 'accounts'

urlpatterns = [
    path('login_user/', views.login_user, name = 'login'),
    path('signup_user/', views.signup_user, name = 'signup'),
    path('logout_user/', views.logout_user, name = 'logout_user'),
    path('bios/', views.bios, name = 'bios'),
    path('password_change/', views.password_change, name = 'password_change'),
    path('change_email/', views.change_email, name = 'change_email'),
    path('verify_email/', views.verify_email, name = 'verify_email'),
    
   #reset password
    path('accounts/password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

acetelproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('',include('acetelapp.urls', namespace='acetelapp')),
    path('subscription/', include('subscription.urls', namespace='subscription')),

    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscription/urls.py
from django.urls import path
from . import views

app_name = 'subscription'

urlpatterns = [
    path('payment_init/<int:course_id>/', views.payment_init, name = 'payment_init'),
    path('processpayment/<int:course_id>/', views.processpayment, name = 'processpayment'),
    path('exam_payment_init/<int:exam_id>/', views.exam_payment_init, name = 'exam_payment_init'),
    path('exam_processpayment/<int:exam_id>/', views.exam_processpayment, name = 'exam_processpayment'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('success/<int:course_id>/', views.success, name='success'),
]

subscription/models.py
import secrets
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone


from acetelapp.models import Course, Exam

# Create your models here.

class RegisteredCourse(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    currency = models.CharField(max_length=50, null=True, default='NGN')
    email = models.EmailField()
    amount = models.PositiveBigIntegerField()
    paystack_ref = models.CharField(max_length=15, blank=True)
    date_created = models.DateTimeField(default=timezone.now)
        
    class Meta:
        ordering = ('-date_created',)
    
    def __str__(self):
        return f"user: {self.user.email} ({self.user.first_name}) - amount: {self.amount}"
    
    def get_amount(self):
        return self.amount
    
    def save(self, *args, **kwargs):
        while not self.paystack_ref:
            ref = secrets.token_urlsafe(50)
            object_with_similar_paystack_ref = RegisteredCourse.objects.filter(paystack_ref=ref)
            if not object_with_similar_paystack_ref:
                self.paystack_ref = ref
        super().save(*args, **kwargs)

    

class RegisteredExam(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    currency = models.CharField(max_length=50, null=True, default='NGN')
    email = models.EmailField()
    amount = models.IntegerField()
    paystack_ref = models.CharField(max_length=15, blank=True)
    date_created = models.DateTimeField(default=timezone.now)
   

    class Meta:
        ordering = ('-date_created',)
    
    def __str__(self):
        return f"user: {self.user.email} ({self.user.first_name}) - amount: {self.amount}"
    
    def get_amount(self):
        return self.amount
    
    def save(self, *args, **kwargs):
        while not self.paystack_ref:
            ref = secrets.token_urlsafe(50)
            object_with_similar_paystack_ref = RegisteredExam.objects.filter(paystack_ref=ref)
            if not object_with_similar_paystack_ref:
                self.paystack_ref = ref
        super().save(*args, **kwargs)



        

subscription/forms.py
from django import forms
from .models import RegisteredCourse

class RegisteredCourseForm(forms.ModelForm):
    class Meta:
        model = RegisteredCourse
        fields = ['user','course', 'currency', 'email', 'amount', 'paystack_ref']

    def __init__(self, user_id=None, course=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Set the initial values for the 'user' and 'course' fields
        self.initial['user'] = user_id
        self.initial['course'] = course

subscription/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from acetelapp.models import Course, Exam
import json
import requests
from django.conf import settings
from .models import RegisteredCourse
from django.contrib import messages


def payment_init(request, course_id):
    
    course = get_object_or_404(Course, pk=course_id)

    return render(request,'subscription/payment.html', {'course': course})


def exam_payment_init(request, exam_id):
    
    exam = get_object_or_404(Exam, pk=exam_id)

    if request.method == 'POST':
        email = request.POST.get('email')
        amount = request.POST.get('amount')

        registered_exam = RegisteredExam.objects.create(email=email, amount=amount, exam=exam, user=request.user)
        registered_exam.save()

        return render(request, 'subscription/success.html', {'exam': exam})
    

    return render(request,'subscription/exam_payment.html', {'exam': exam})


api_key = settings.PAYSTACK_SECRET_KEY
url = settings.PAYSTACK_INITIALIZE_PAYMENT_URL

def processpayment(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    
    if request.method == 'POST':
        email = request.POST.get('email')
        amount = request.POST.get('amount')

        # check if the registered course already exist
        registered_courses = RegisteredCourse.objects.filter(user=request.user)
        if registered_courses.filter(course__title=course.title).exists():
            messages.success(request, "You have already subscribed to this course.")
            # Redirect to an error page or display a message indicating the payment cannot proceed
            return redirect('acetelapp:mycourse')

        # Create and save the RegisteredCourse object
        registered_course = RegisteredCourse.objects.create(email=email, amount=amount, course=course, user=request.user)
       
              
        success_url = request.build_absolute_uri(reverse('subscription:success',  kwargs={'course_id':course_id}))
        cancel_url = request.build_absolute_uri(reverse('subscription:canceled'))
    
        metadata = json.dumps({"course_id":course_id, "cancel_action": cancel_url})
       
        # Paystack checkout session data
        api_key = settings.PAYSTACK_SECRET_KEY
        session_data = {'email': email, 'amount': int(float(amount))*100, 'callback_url': success_url, 'metadata': metadata}
        headers = {"authorization": f"Bearer {api_key}"}
        
        # API request to Paystack server
        
        r = requests.post(url, headers=headers, json=session_data)
        response = r.json()
    
        if response.get("status"):
            # Redirect to Paystack payment form
            redirect_url = response["data"]["authorization_url"]
            
            return redirect(redirect_url, code=303)
        else:
            return render(request, 'subscription/payment.html', {'course': course, 'error': response.get("message")})

    return render(request, 'subscrition/payment.html', {'course': course})

def success(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    messages.success(request, f"You have successfully subscribed to {course.title}")

    return redirect('acetelapp:mycourse')


def exam_processpayment(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    
    if request.method == 'POST':
        email = request.POST.get('email')
        amount = request.POST.get('amount')
        
        success_url = request.build_absolute_uri(reverse('subscription:exam_payment_init', kwargs={'exam_id':exam_id}))
        cancel_url = request.build_absolute_uri(reverse('subscription:canceled'))
    
        metadata = json.dumps({"exam_id":exam_id, "cancel_action": cancel_url})
       
        # Paystack checkout session data
        api_key = settings.PAYSTACK_SECRET_KEY
        session_data = {'email': email, 'amount': int(float(amount)) * 100, 'callback_url': success_url, 'metadata': metadata}
        headers = {"authorization": f"Bearer {api_key}"}
        
        # API request to Paystack server
        url = 'https://api.paystack.co/checkout/initialize'
        r = requests.post(url, headers=headers, json=session_data)
        response = r.json()
    
        if response.get("status"):
            # Redirect to Paystack payment form
            redirect_url = response["data"]["authorization_url"]
            return redirect(redirect_url, code=303)
        else:
            return render(request, 'subscription/exam_payment.html', {'exam':exam, 'error': response.get("message")})

    return render(request, 'subscription/exam_payment.html', {'exam':exam})



def payment_canceled(request):
 return render(request, 'subscription/canceled.html')

subscription/templates/subscription/exam_payment.html
<!DOCTYPE html>
<html lang="en" id="html">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://js.paystack.co/v1/inline.js"></script>

    <style>
        .one {
            width: 740px;
        }

        input {
            border: none;
        }

        form {
            background-color: rgb(156 151 151 / 13%);
        }
    </style>
</head>

<body>
    <div class="card container-sm one" style="margin-top: 4rem; border: none;">
        <h3>Payment</h3>
        <h6>Choose your best payment method below</h6>
    </div>
    <div class="card container-sm one">
        <form  id="myform" method="post" action="{% url 'subscription:exam_processpayment' exam.id  %}" >
            {% csrf_token %}       
            <select id="select_id" onchange="selected()">
                <option value="NGN">Naira</option>
                <option value="$">Dollar</option>
            </select>
            <div class="container-sm" style="padding-bottom: 1rem; text-align: center;">
                <label for="transation" style="color: #055b38; font-size: 2rem;">Complete transaction of <span
                        id="currency">NGN</span></label>
                <input type="text" name="amount"  value="{{exam.amount}}"
                    style="color: #055b38; font-size: 2rem; width:100px;">
            </div>
            <div class="container-sm d-flex justify-content-between">
                <div class="card" style="width: 49%;">
                    <img src="{{exam.image.url}}" alt="">
                </div>
                <div class="" style="width: 49%;">
                    <input type="email" name="email"  value="{{user.email}}"
                        style="width: 100%; font-size: 1.5rem;"><br>
                    <input type="text"  name="title" value="{{exam.title}}"
                        style="font-size: 1.5rem;"><br>
                    <label style="font-weight: bold;">Description</label>
                    <p>
                        {{exam.description}}
                    </p>
                </div>
            </div>
            <div class="container-sm" style="padding: 1rem; text-align:right">
                <button class="btn btn-primary" type="submit" style="background-color: #055b38;">Pay Now</button>
            </div>
           
        </form>

    </div>
    <script>     
        let currency = document.getElementById("currency");
        function selected() {
            currency.innerHTML = document.getElementById("select_id").value;
        }

    </script>
</body>

</html>

subscription/templates/subscription/payment.html
<!DOCTYPE html>
<html lang="en" id="html">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://js.paystack.co/v1/inline.js"></script>

    <style>
        .one {
            width: 740px;
        }

        input {
            border: none;
        }

        form {
            background-color: rgb(156 151 151 / 13%);
        }
    </style>
</head>

<body>
    <div class="card container-sm one" style="margin-top: 4rem; border: none;">
        <h3>Payment</h3>
        <h6>Choose your best payment method below</h6>
    </div>
    <div class="card container-sm one">
        <form  id="myform" method="post" action="{% url 'subscription:processpayment' course.id  %}" >
            {% csrf_token %}       
            <select id="select_id" onchange="selected()">
                <option value="NGN">Naira</option>
                <option value="$">Dollar</option>
            </select>
            <div class="container-sm" style="padding-bottom: 1rem; text-align: center;">
                <label for="transation" style="color: #055b38; font-size: 2rem;">Complete transaction of <span
                        id="currency">NGN</span></label>
                <input type="text" name="amount"  value="{{course.amount}}"
                    style="color: #055b38; font-size: 2rem; width:100px;">
            </div>
            <div class="container-sm d-flex justify-content-between">
                <div class="card" style="width: 49%;">
                    <img src="{{course.image.url}}" alt="">
                </div>
                <div class="" style="width: 49%;">
                    <input type="email" name="email"  value="{{user.email}}"
                        style="width: 100%; font-size: 1.5rem;"><br>
                    <input type="text"  name="title" value="{{course.title}}"
                        style="font-size: 1.5rem;"><br>
                    <label style="font-weight: bold;">Description</label>
                    <p>
                        {{course.description}}
                    </p>
                </div>
            </div>
            <div class="container-sm" style="padding: 1rem; text-align:right">
                <button class="btn btn-primary" type="submit" style="background-color: #055b38;">Pay Now</button>
            </div>
           
        </form>

    </div>
    <script>     
        let currency = document.getElementById("currency");
        function selected() {
            currency.innerHTML = document.getElementById("select_id").value;
        }

    </script>
</body>

</html>

subscription/templates/subscription/success.html
{% extends 'acetelapp/login_base.html' %}

{% block content%}
<div class="container mt-3">
    <h1>Your payment was successful</h1>
    <p>Your payment has been processed successfully.</p>
</div>
{% endblock %}