accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from accounts.views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

app_name = 'accounts'

urlpatterns = [
    path('login_user/', views.login_user, name = 'login'),
    path('signup_user/', views.signup_user, name = 'signup'),
    path('logout_user/', views.logout_user, name = 'logout_user'),
    path('bios/', views.bios, name = 'bios'),
    path('password_change/', views.password_change, name = 'password_change'),
    path('change_email/', views.change_email, name = 'change_email'),
    path('verify_email/', views.verify_email, name = 'verify_email'),
    
   #reset password
    path('accounts/password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

acetelapp/urls.py
from django.urls import path
from . import views

app_name ='acetelapp'

urlpatterns = [
   path('', views.index, name='index'),
   path('courses/', views.courses, name='courses'),
   path('exams/', views.exams, name='exams'),
   path('login_courses/', views.login_courses, name='login_courses'),
   path('login_exams/', views.login_exams, name='login_exams'),
   path('login_page/', views.login_page, name='login_page'),
   path('mycourse/', views.mycourse, name='mycourse'),
   path('myexams/', views.myexams, name='myexams'),
   path('registercourse/<int:course_id>/', views.registercourse, name ='registercourse'),
   path('registerexam/<int:exam_id>/', views.registerexam, name ='registerexam')
]

acetelproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('',include('acetelapp.urls', namespace='acetelapp')),
    path('subscription/', include('subscription.urls', namespace='subscription')),

    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class CustomUserManager(BaseUserManager):
    def create_user(self, first_name, last_name, email, phone_number, password, **extra_fields):
        # Validate the email and password
        if not email:
            raise ValueError('Email must be a valid email address')
        if not password:
            raise ValueError('Password must be a valid password')
       
        
        user = self.model(
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email),
            phone_number=phone_number,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    
    def create_superuser(self, first_name, last_name, email, phone_number, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        
        return self.create_user(first_name, last_name, email, phone_number, password, **extra_fields)



#Create CustomUser Modele here 
class User(AbstractBaseUser,PermissionsMixin):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField(db_index=True, unique=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    
    
    is_staff = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name', 'phone_number']

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return self.first_name


class Profile(models.Model):
    #creating gender choices
    GENDER_CHOICES=(
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    profile_pic = models.ImageField(default='default.jpg', upload_to='profile_pics')
   

    # Add any additional fields and methods as needed

    def __str__(self):
        return self.user.first_name

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile 
from accounts.models import User
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm, UserCreationForm
from django.contrib.auth import password_validation
from django.utils.translation import gettext, gettext_lazy as _
from django.core.validators import RegexValidator
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm


 


#customUserCreationForm
class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.',
                                            widget=forms.TextInput(attrs={'class': 'form-control col-md-6'}))
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.',
                                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=200, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(max_length=30, required=True, help_text='Required.',
                                            widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(max_length=30, required=True, help_text='Required.',
                                            widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    
    class Meta:
        model = User
        fields =('first_name','last_name', 'email', 'phone_number','password1','password2',)

        def clean_password1(self):
            password1 = self.cleaned_data.get('password1')
            password_validation.validate_password(password1, self.instance)
            return password1 


#creating update form for user
class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=150, 
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name']


class UpdateProfileForm(forms.ModelForm):
    GENDER_CHOICES=(
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    profile_pic = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Profile
        fields = ['gender', 'profile_pic']

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Customize the form fields here (if needed)
        self.fields['old_password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Old Password'})
        self.fields['new_password1'].widget.attrs.update({'class': 'form-control', 'placeholder': 'New Password'})
        self.fields['new_password2'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Confirm New Password'})

class ChangeEmailForm(UserChangeForm):
    email = forms.EmailField(label='New Email', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'New Email'}))


    class Meta:
        model = User
        fields = ('email',)


#Password ResetForm
class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(max_length=200, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is not registered.")
        return email
    
    


class CustomPasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(max_length=30, required=True, help_text='Required.',
                                            widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(max_length=30, required=True, help_text='Required.',
                                            widget=forms.PasswordInput(attrs={'class': 'form-control'}))

accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import UpdateProfileForm, UpdateUserForm
from .forms import CustomPasswordChangeForm, ChangeEmailForm, CustomUserCreationForm
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from accounts.forms import CustomPasswordResetForm, CustomPasswordResetConfirmForm
from acetelapp.views import courses, exams
from . models import Profile, User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy




# Create your views here.
def signup_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            messages.success(request, 'Successfully registered, Login')
            return redirect('accounts:login')
        
    else:
        # If the request method is GET, create a new form instance
        form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form}) 
    

def login_user(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('acetelapp:login_page')  # Replace 'dashboard' with your desired URL or view name
        else:
            messages.error(request, 'Email or Password Incorrect')
            return render(request, 'accounts/login.html', {'error': 'Invalid email or password.'})
    else:
        return render(request, 'accounts/login.html')


def logout_user(request):
    logout(request)
    return redirect('acetelapp:index')


@login_required
def bios(request):
     
    if request.method == 'POST':
        user_form =UpdateUserForm(request.POST, instance = request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)
        

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect('accounts:bios')
    else:
        user_first_letter = request.user.first_name[0]
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)
       
    context = {
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
        'user_first_letter': user_first_letter,
        'courses': courses,
        'exams': exams,
        'user_form': user_form,
        'profile_form': profile_form,
        
    }
    return render(request, 'accounts/bios.html', context)

@login_required
def password_change(request):
    user_first_letter = request.user.first_name[0]

    context = {
        'first_name': request.user.first_name,
        'user_first_letter': user_first_letter,
        'courses': courses,
        'exams': exams,
    }
    return render(request, 'accounts/password_change.html', context)


@login_required
def verify_email(request):
    user_first_letter = request.user.first_name[0]
    
    context = {
        'first_name': request.user.first_name,
        'user_first_letter': user_first_letter,
        'courses': courses,
        'exams': exams,
    }
    return render(request, 'accounts/verify_email.html', context)


@login_required
def password_change(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Your password was successfully changed.')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = CustomPasswordChangeForm(request.user)
        
        context = {
        'first_name': request.user.first_name,
        'user_first_letter':request.user.first_name[0],
        'form': form,  
    }

    return render(request, 'accounts/password_change.html', context)


@login_required
def change_email(request):
    if request.method == 'POST':
        form = ChangeEmailForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your email address has been updated.')
            return redirect('accounts:change_email')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = ChangeEmailForm(instance=request.user)

        context = {
        'first_name': request.user.first_name,
        'user_first_letter':request.user.first_name[0],
        'form': form,  
    }

    return render(request, 'accounts/change_email.html', context)


class CustomPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    email_template_name = 'accounts/password_reset_email.html'
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy('accounts:password_reset_done')
    
    


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')
    form_class = CustomPasswordResetConfirmForm

class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

accounts/templates/accounts/bios.html
{% extends 'acetelapp/login_base.html' %}
{% load static %}

{% block content %}
    <div class="section settings-nav" >
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'accounts:bios' %}">BIOS</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:password_change' %}">CHANGE PASSWORD</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:change_email' %}">CHANGE GMAIL</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'accounts:verify_email' %}" >EMAIL VERIFICATION</a>
                </li>
              </ul>
    </div>
    
    <div class="form-section settings-nav">
        <form  method="post" enctype="multipart/form-data">
            {% for message in messages %}
              <div class="alert alert-success" role="alert">
                {{message}}
              </div>
              {% endfor %}
          {% csrf_token %}
            <div style="text-align: center;"><h2>Bio Settings</h2></div>

            <div class="mb-3">
                <fieldset>
                    <legend>First name*</legend>
                    {{user_form.first_name}}
                </fieldset>
                <fieldset>
                    <legend>Surname*</legend>
                   {{user_form.last_name}}
                </fieldset>
                <fieldset>
                    {{profile_form.gender}}
                </fieldset>
                <fieldset>
                    {{profile_form.profile_pic}}
                </fieldset>
                <fieldset>
                <div class="col-auto" style="text-align:center;">
                    <button type="submit" class="btn btn-primary">Update Bio</button>
                </div>
                </fieldset>
              </div>
        </form>
    </div>
    

{% endblock %}

accounts/templates/accounts/change_email.html
{% extends 'acetelapp/login_base.html' %}
{% load static %}

{% block content %}
    <div class="section settings-nav" >
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'accounts:bios' %}">BIOS</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:password_change' %}">CHANGE PASSWORD</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:change_email' %}">CHANGE GMAIL</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'accounts:verify_email' %}" >EMAIL VERIFICATION</a>
                </li>
              </ul>
    </div>
    <div class="form-section settings-nav">
        <form method="post">
          {% csrf_token %}
            <div style="text-align: center;">
                <h2>Email Settings</h2>
            </div>

            <div class="mb-3">
                <fieldset>
                  {{form.email}}  
                </fieldset>
                <fieldset>
                    <div class="col-auto" style="text-align:center ;">
                        <button type="submit" class="btn btn-primary">Change Email</button>
                    </div>
                </fieldset>
            </div>

        </form>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/login_section.css' %} " rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="section login_section">
        <div class="login_box">
           <img src="{% static 'images/createAccount.jpg' %}" alt="" class="box_image"> 
        </div>
        <div class="login_box">
          <a href="{% url 'acetelapp:index' %}"><img src="{% static 'images/home_icon.JPG' %}" alt="" class="home_icon"></a>
            <h2>Welcome Back</h2>
            {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
               {{message}}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            <form action="" method="post">
                  {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Email or Username</label>
                    <input type="email" name="email" class="form-control" id="username" placeholder="Enter your email">
                  </div>
                  <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                  </div>
                  <div class="mb-3">
                    <Span><a href="{% url 'accounts:password_reset' %}">Forget password?</a></Span>
                  </div>
                  <div class="mb-3">
                    <input type="submit" class="form-control" id="submit" value="Login" style="background-color:#97b9f0; color:white">
                  </div>
                  <div class="mb-3">
                    <Span>Do you have an account?<a href="{% url 'accounts:signup' %}">&nbsp;<b>Register</b></a></Span>
                  </div>
            </form>  
        </div> 
    
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <script src="javascript.js"></script>
</body>
</html>

accounts/templates/accounts/password_change.html
{% extends 'acetelapp/login_base.html' %}
{% load static %}

{% block content %}
    <div class="section settings-nav" >
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'accounts:bios' %}">BIOS</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:password_change' %}">CHANGE PASSWORD</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:change_email' %}">CHANGE GMAIL</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'accounts:verify_email' %}" >EMAIL VERIFICATION</a>
                </li>
              </ul>
    </div>
    <div class="form-section settings-nav">
      <form method="post">
        {% csrf_token %}
        <div style="text-align: center;">
            <h2>Password Settings</h2>
        </div>

        <div class="mb-3">
            {{ form.as_p }}
            <div class="col-auto" style="text-align: center;">
                <button type="submit" class="btn btn-primary">Change Password</button>
            </div>
        </div>
    </form>          
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/login_section.css' %} " rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="section login_section">
        <div class="login_box">
            <img src="{% static 'images/createAccount.jpg' %}" alt="" class="box_image">
        </div>
        <div class="login_box">
            <a href="{% url 'acetelapp:index' %}"><img src="{% static 'images/home_icon.JPG' %}" alt="" class="home_icon"></a>
            <h1>Your password has been successfully Changed</h1>
            <p>Click the the link below to login</p>
            <a href="{% url 'accounts:login' %}" style="text-decoration: underline;">Go to login</a>
        </div> 
    
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <script src="javascript.js"></script>
</body>
</html>

accounts/templates/accounts/password_reset_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/login_section.css' %} " rel="stylesheet" type="text/css" />

</head>

<body>
    <div class="section login_section">
        <div class="login_box">
            <img src="{% static 'images/createAccount.jpg' %}" alt="" class="box_image">
        </div>
        <div class="login_box">
            <a href="{% url 'acetelapp:index' %}"><img src="{% static 'images/home_icon.JPG' %}" alt="" class="home_icon"></a>
            <h1>Reset your password</h1>
            {% if validlink %}
            <p>Please enter your new password twice:</p>
            <form class="row g-3" method="post">
                {% csrf_token %}      
                <div class="col-md-12">
                  <label for="password" class="form-label">Enter New Password*</label>
                  {{form.new_password1}}
                </div>
                <div class="col-md-12">
                  <label for="lastname" class="form-label">Confirm New Password*</label>
                  {{form.new_password2}}
                </div>
                <div class="col-md-6">
                  {% for field in form %}
                    {% for error in field.errors %}
                      <p style="color:red">{{ error }}</p>
                    {% endfor %}
                  {% endfor %}
                </div>
                <div class="mb-3">
                  <input type="submit" class="form-control" id="submit" value="Reset"
                    style="background-color:#97b9f0; color:white">
                </div>
              </form>
            {% else %}
            <p>The password reset link was invalid, possibly because it has already
                been used. Please request a new password reset.</p>
            {% endif %}
        </div>

    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <script src="javascript.js"></script>
</body>

</html>

accounts/templates/accounts/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/login_section.css' %} " rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="section login_section">
        <div class="login_box">
            <img src="{% static 'images/createAccount.jpg' %}" alt="" class="box_image">
        </div>
        <div class="login_box">
            <a href="{% url 'acetelapp:index' %}"><img src="{% static 'images/home_icon.JPG' %}" alt="" class="home_icon"></a>
            <h1>Reset your password</h1>
            <p>We've emailed you instructions for setting your password.</p>
            <p>If you don't receive an email, please make sure you've entered the address 
               you registered with.</p> 
        </div> 
    
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <script src="javascript.js"></script>
</body>
</html>

accounts/templates/accounts/password_reset_email.html
{% load i18n %}
{% autoescape off %}
Hello,

You're receiving this email because you requested a password reset for your account at {{ site_name }}.

Please go to the following page to reset your password:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If you didn't request a password reset, please ignore this email.

Thanks,
The {{ site_name }} Team
{% endautoescape %}

accounts/templates/accounts/settings_nav.html
{% load static %}
<div class="section settings-nav" >
    <ul class="nav nav-pills nav-fill">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:bios' %}">BIOS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:change_password' %}">CHANGE PASSWORD</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:change_email' %}">CHANGE GMAIL</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'accounts:verify_email' %}" >EMAIL VERIFICATION</a>
        </li>
      </ul>
</div>
{% block content %}
    
{% endblock %}

accounts/templates/accounts/verify_email.html
{% extends 'acetelapp/login_base.html' %}
{% load static %}

{% block content %}
    <div class="section settings-nav" >
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'accounts:bios' %}">BIOS</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:password_change' %}">CHANGE PASSWORD</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:change_email' %}">CHANGE GMAIL</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'accounts:verify_email' %}" >EMAIL VERIFICATION</a>
                </li>
              </ul>
    </div>
    <div class="form-section settings-nav">
        <form action="">
            <div style="text-align: center;">
                <h2>Email Verification</h2>
            </div>

            <div class="mb-3">
                <fieldset>
                    <div class="col-auto" style="text-align:center ;">
                        <button type="submit" class="btn btn-primary">Resent Email Verification Link</button>
                    </div>
                </fieldset>
            </div>

        </form>
    </div>
{% endblock %}