accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from accounts.views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

app_name = 'accounts'

urlpatterns = [
    path('login_user/', views.login_user, name = 'login'),
    path('signup_user/', views.signup_user, name = 'signup'),
    path('logout_user/', views.logout_user, name = 'logout_user'),
    path('bios/', views.bios, name = 'bios'),
    path('password_change/', views.password_change, name = 'password_change'),
    path('change_email/', views.change_email, name = 'change_email'),
    path('verify_email/', views.verify_email, name = 'verify_email'),
    
   #reset password
    path('accounts/password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

acetelapp/urls.py
from django.urls import path
from . import views

app_name ='acetelapp'

urlpatterns = [
   path('', views.index, name='index'),
   path('courses/', views.courses, name='courses'),
   path('exams/', views.exams, name='exams'),
   path('login_courses/', views.login_courses, name='login_courses'),
   path('login_exams/', views.login_exams, name='login_exams'),
   path('login_page/', views.login_page, name='login_page'),
   path('mycourse/', views.mycourse, name='mycourse'),
   path('myexams/', views.myexams, name='myexams'),
   path('registercourse/<int:course_id>/', views.registercourse, name ='registercourse'),
   path('registerexam/<int:exam_id>/', views.registerexam, name ='registerexam')
]

acetelproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('',include('acetelapp.urls', namespace='acetelapp')),
    path('subscription/', include('subscription.urls', namespace='subscription')),

    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscription/urls.py
from django.urls import path
from . import views

app_name = 'subscription'

urlpatterns = [
    path('payment_init/<int:course_id>/', views.payment_init, name = 'payment_init'),
    path('processpayment/<int:course_id>/', views.processpayment, name = 'processpayment'),
    path('exam_payment_init/<int:exam_id>/', views.exam_payment_init, name = 'exam_payment_init'),
    path('exam_processpayment/<int:exam_id>/', views.exam_processpayment, name = 'exam_processpayment'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('success/<int:course_id>/', views.success, name='success'),
]

acetelapp/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    image =models.ImageField(upload_to = 'images')
    title = models.CharField(max_length=225)
    description = models.TextField(max_length=225)
    date = models.DateTimeField(auto_now_add=True)
    amount = models.IntegerField()

    def __str__(self):
        return self.title


class Exam(models.Model):
    image =models.ImageField(upload_to = 'images')
    title = models.CharField(max_length=225)
    description = models.TextField(max_length=225)
    amount = models.IntegerField()
    question = models.IntegerField()

    def __str__(self):
        return self.title

acetelapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count
from subscription.models import RegisteredCourse, RegisteredExam
from . models import Course, Exam
from accounts.models import User
from django.contrib.auth import authenticate, login 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from datetime import timedelta



# Create your views here.
def index(request):
    exams = Exam.objects.all()
    #Get couses according to number of subscribers
    courses = Course.objects.annotate(num_users_registered=Count('registeredcourse'))
 
    for course in courses:
        duration = timezone.now() - course.date
        minutes = duration.total_seconds() / 60

        if minutes < 1:
            course.date= "Just Now"
        elif minutes < 60:
            course.date= f"{int(minutes)} minutes ago"
        elif minutes < 1440: 
            course.date =f"{int(minutes // 60)} hours ago"
        else:
            days = duration.days
            if days == 1:
                course.date="1 day ago"
            else:
                course.date =f"{days} days ago"
    
    context = {
        'courses': courses,
        'exams': exams,
                    
    }

    return render(request, 'acetelapp/index.html', context)

   
    
def courses(request):
    #Get couses according to number of subscribers
    courses = Course.objects.annotate(num_users_registered=Count('registeredcourse'))
    for course in courses:
        duration = timezone.now() - course.date
        minutes = duration.total_seconds() / 60

        if minutes < 1:
            course.date= "Just Now"
        elif minutes < 60:
            course.date= f"{int(minutes)} minutes ago"
        elif minutes < 1440: 
            course.date =f"{int(minutes // 60)} hours ago"
        else:
            days = duration.days
            if days == 1:
                course.date="1 day ago"
            else:
                course.date =f"{days} days ago"
    
    context = {
        'courses': courses,
        'exams': exams,
            
    }
    context = {
        'courses':courses
    }
    return render(request, 'acetelapp/courses.html', context)

def exams(request):
    exams = Exam.objects.all()
    context = {
        'exams': exams
    }
    return render(request, 'acetelapp/exams.html', context)


def login_page(request):
    #Get couses according to number of subscribers
    courses = Course.objects.annotate(num_users_registered=Count('registeredcourse'))
    exams = Exam.objects.all()
    if request.user.is_authenticated:
        user = request.user
        login(request, user)
        first_name = user.first_name
        user_first_letter = user.first_name[0]
    else:
        return redirect('accounts:login')
    
    for course in courses:
        duration = timezone.now() - course.date
        minutes = duration.total_seconds() / 60

        if minutes < 1:
            course.date= "Just Now"
        elif minutes < 60:
            course.date= f"{int(minutes)} minutes ago"
        elif minutes < 1440: 
            course.date =f"{int(minutes // 60)} hours ago"
        else:
            days = duration.days
            if days == 1:
                course.date="1 day ago"
            else:
                course.date =f"{days} days ago"

    context = {
        'first_name': first_name,
        'user_first_letter': user_first_letter,
        'courses': courses,
        'exams': exams,
    }
    return render(request, 'acetelapp/login_page.html', context)

def login_courses(request):
    #Get couses according to number of subscribers
    courses = Course.objects.annotate(num_users_registered=Count('registeredcourse'))
       
    if request.user.is_authenticated:
        user = request.user
        login(request, user)
        first_name = user.first_name
        user_first_letter = user.first_name[0]
    else:
        return redirect('accounts:login')

    for course in courses:
        duration = timezone.now() - course.date
        minutes = duration.total_seconds() / 60

        if minutes < 1:
            course.date= "Just Now"
        elif minutes < 60:
            course.date= f"{int(minutes)} minutes ago"
        elif minutes < 1440: 
            course.date =f"{int(minutes // 60)} hours ago"
        else:
            days = duration.days
            if days == 1:
                course.date="1 day ago"
            else:
                course.date =f"{days} days ago"
    
    context = {
        'first_name': first_name,
        'user_first_letter': user_first_letter,
        'courses': courses,
        'exams': exams,
    }

    return render(request, 'acetelapp/login_courses.html', context)

def login_exams(request):
    exams = Exam.objects.all()
    if request.user.is_authenticated:
        user = request.user
        login(request, user)
        first_name = user.first_name
        user_first_letter = user.first_name[0]
    else:
        return redirect('accounts:login')

    context = {
        'first_name': first_name,
        'user_first_letter': user_first_letter,
        'courses': courses,
        'exams': exams,
    }

    return render(request, 'acetelapp/login_exams.html', context)

def mycourse(request):
    user = request.user
    # Fetch the registered courses for the current user
    registered_courses = RegisteredCourse.objects.filter(user=user)
    #Get couses according to number of subscribers
    registered_courses = registered_courses.annotate(num_users=Count('course__registeredcourse'))
    
    if request.user.is_authenticated:
        user = request.user
        login(request, user)
        first_name = user.first_name
        user_first_letter = user.first_name[0]
    else:
        return redirect('accounts:login')

    for registered_course in registered_courses:
        duration = timezone.now() - registered_course.course.date
        minutes = duration.total_seconds() / 60

        if minutes < 1:
            registered_course.course.date= "Just Now"
        elif minutes < 60:
            registered_course.course.date= f"{int(minutes)} minutes ago"
        elif minutes < 1440: 
            registered_course.course.date =f"{int(minutes // 60)} hours ago"
        else:
            days = duration.days
            if days == 1:
                registered_course.course.date="1 day ago"
            else:
                registered_course.course.date =f"{days} days ago"

    context = {
        'courses':courses,
        'first_name': first_name,
        'user_first_letter': user_first_letter,
        'registered_courses': registered_courses,
        'registered_courses': registered_courses,
    }

    return render(request, 'acetelapp/mycourse.html', context)

def myexams(request):
    registered_exams=RegisteredExam.objects.all()
    if request.user.is_authenticated:
        user = request.user
        login(request, user)
        first_name = user.first_name
        user_first_letter = user.first_name[0]
    else:
        return redirect('accounts:login')

    context = {
        'first_name': first_name,
        'user_first_letter': user_first_letter,
        'registered_exams':registered_exams,
    }
   
    return render(request, 'acetelapp/myexams.html', context)


def registercourse(request, course_id):
    course = get_object_or_404(Course, id = course_id)
    if request.user.is_authenticated:
        user = request.user
        login(request, user)
        first_name = user.first_name
        user_first_letter = user.first_name[0]
    else:
        return redirect('accounts:login')
    context ={
        'course' : course,
        'first_name' : first_name,
        'user_first_letter':user_first_letter,
    }
    return render (request,'acetelapp/registercourse.html', context )



def registerexam(request, exam_id):
    exam = get_object_or_404(Exam, id=exam_id)
    if request.user.is_authenticated:
        user = request.user
        login(request, user)
        first_name = user.first_name
        user_first_letter = user.first_name[0]
    else:
        return redirect('accounts:login')
    context ={
        'exam' : exam,
        'first_name' : first_name,
        'user_first_letter':user_first_letter,
        }
    return render (request,'acetelapp/registerexam.html', context  )

acetelapp/templates/acetelapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" id="html">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css">
    <title>LearnNow</title>
    <link rel="icon" type="image/png" href="{% static 'images/home_icon.JPG' %}">
</head>

<body>
    <div id="header" class="section header">
        <a href="{% url 'acetelapp:index' %}"><img src ="{% static 'images/home_icon.JPG' %}"></a>
        <div class="nav-bar">
            <ul class="home">
                <li><a href="{% url 'acetelapp:index' %}">Home</a></li>
                <li><a href="{% url 'acetelapp:courses' %}">Courses</a></li>
                <li><a href="{% url 'acetelapp:exams' %}">Exam</a></li>
            </ul>
            <ul>
                <li class="login"><a href="{% url 'accounts:login' %}"><span>Lo</span>g<span>in</span></a></li>
                <li class="register"><a href="{% url 'accounts:signup' %}">Register</a></li>
            <ul>
        </div>
        <i onclick="hiddenNav()" class="fas fa-bars"></i>
    </div>
    <div id="hidden-nav" class="hidden-nav">
        <div class="hidden-nav-bar">
            <a href="#"><img src ="{% static 'images/home_icon.JPG' %}"></a>
            <hr>
            <ul>
                <li><a href="{% url 'acetelapp:index' %}">Home</a></li>
                <li><a href="{% url 'acetelapp:courses' %}">Courses</a></li>
                <li><a href="{% url 'acetelapp:exams' %}">Exam</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Create Account</a></li>
                <ul>
        </div>
        <div onclick="closeNav()" class="hidden-nav2"></div>
    </div>

    {% block content %}
    
    {% endblock %}

    <div class="footer">
        <div class="footer-box section">
            <div class = "footer-content" >
                <img src ="{% static 'images/home_icon.JPG' %}" alt="" style="padding-bottom: 15px;">
                <p>The creation of this website for the purporse of learning.
                </p>
            </div>
            <div class = "footer-content" style="padding-right:3rem;">
                <h3>Address:</h3>
                <p>Our Address<br> 
                     Abuja, Nigeria.
                </p>
                <h3>TelePhone:</h3>
                <a href="">08164696712</a>
                <h3>Contact Email</h3>
                <a href="">to_uremail@gmail.com</a> 
            </div>
            <div class = "footer-content last">
                <h3>category</h3>
                <a href="">Courses</a><br>
                <a href="">Exams</a>
            </div>
        </div>
        <h2>Built for the purpose of learning Using Django</h2>
        <a href="#">www.yourwebsite.com</a>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <script src="{% static 'js/javascript.js' %}"></script>
</body>

</html>

acetelapp/templates/acetelapp/courses.html
{% extends 'acetelapp/base.html' %}

{% load static %}

{% block content %}
<div class="browse section">
    <h2>Browse Courses</h2>
    <div class="browse-courses">
        {% for course in courses %}
        <a href="{% url 'acetelapp:registercourse' course_id=course.id %}" class="card-box">
            <div class="card">
                <img src="{{course.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-heading">{{course.title}}</h5>
                    <p class="card-text">{{course.description}}</p>
                    <p style="font-size: 0.9rem;">
                        <i class="far fa-clock" style="color:#055b38"></i> &nbsp;{{course.date}} <i
                            class="fas fa-user-friends" style="color:#055b38"></i> {{course.num_users_registered}}<span
                            style="float: right; font-size: 1.3rem; color:#055b38;">&#8358;{{course.amount}}</span>
                    </p>
                </div>
            </div>
        </a>
        {% endfor %}

    </div>

</div>


{% endblock %}

acetelapp/templates/acetelapp/exams.html
{% extends 'acetelapp/base.html' %}

{% load static %}

{% block content %}

<div class="browse section explore">
    <heading>
        <h2>Explore Top Test/Exams</h2>
    </heading>

    <div class="browse-courses test-exam">
        {% for exam in exams %}
        <a href="{% url 'acetelapp:registerexam' exam_id=exam.id %}" class="card-box">
            <div class="card title-card">
                <img src="{{exam.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-heading">{{exam.title}}</h5>
                    <p class="card-text">{{exam.description}}</p>
                </div>
                <div class="title">
                    <p style="font-size: 0.9rem;">
                        <i class="far fa-comment-alt"></i> &nbsp;{{exam.question}} Questions <span style="float:right"><i
                                class="fas fa-user-friends"></i>&nbsp;227 Subscribers</span>
                    </p>
                </div>
            </div>
        </a>
        {% endfor %}

    </div>
</div>


</div>

{% endblock %}

acetelapp/templates/acetelapp/login_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" id="html">
    {% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/login_section.css' %} " rel="stylesheet" type="text/css" />
    <link href="{% static 'css/settings.css' %} " rel="stylesheet" type="text/css" />
    <title>LearnNow</title>
    <link rel="icon" type="image/png" href="{% static 'images/home_icon.JPG' %}">
</head>

<body>
    
    <div id="header" class="section header">
        <a href="{% url 'acetelapp:login_page' %}"><img src="{% static 'images/home_icon.JPG' %}"></a>
        <div class="nav-bar">
            <ul class="home">
                <li><a href="{% url 'acetelapp:login_page' %}">Home</a></li>
                <li><a href="{% url 'acetelapp:login_courses' %}">Courses</a></li>
                <li><a href="{% url 'acetelapp:mycourse' %}">My Courses</a></li>
                <li><a href="{% url 'acetelapp:login_exams' %}">Exams</a></li>
                <li><a href="{% url 'acetelapp:myexams' %}">My Exams</a></li>
            </ul>
            <ul class="home">
                <li style="cursor: pointer;" onclick="displaySettings()"><a href="#" 
                    style ="border-radius: 50%; background-color: gray; padding: 0.7rem; color: white;">{{user_first_letter}}</a><Span>{{first_name}}</Span>              
                </li>
   
            <ul>
        </div>
       <div>
        <i onclick="hiddenNav()" class="fas fa-bars"></i>
       </div>    
    </div>
    <div class="settings" id="settings">
        <ul >
            <li><i class="fas fa-chalkboard-teacher"></i><a href="{% url 'acetelapp:mycourse' %}">My Courses</a></li>
            <li><i class="fas fa-diagnoses"></i><a href="{% url 'acetelapp:myexams' %}">My Exams</a></li>
            <li><i class="fas fa-user-cog"></i><a href="{% url 'accounts:bios' %}">Profile settings</a></li>
            <li><i class="fas fa-sign-out-alt"></i><a href="{% url 'accounts:logout_user' %}">Logout</a></li>
        </ul>
    </div> 
    <div id="hidden-nav" class="hidden-nav">
        <div class="hidden-nav-bar">
            <a href="#"><img src="{% static 'images/home_icon.JPG' %}"></a>
            <hr>
            <ul>
                <li><a href="{% url 'acetelapp:login_page' %}">Home</a></li>
                <li><a href="{% url 'acetelapp:login_courses' %}">Courses</a></li>
                <li><a href="{% url 'acetelapp:mycourse' %}">My Courses</a></li>
                <li><a href="{% url 'acetelapp:login_exams' %}">Exams</a></li>
                <li><a href="{% url 'acetelapp:myexams' %}">My Exams</a></li>
                <li><a href="{% url 'accounts:logout_user' %}">logout</a></li>
            <ul>
        </div>
        <div onclick="closeNav()" class="hidden-nav2"></div>
    </div>
   

    {% block content %}
    
    {% endblock %}

    <div class="footer">
        <div class="footer-box section">
            <div class = "footer-content" >
                <img src ="{% static 'images/home_icon.JPG' %}" alt="" style="padding-bottom: 15px;">
                <p>The creation of this website for the purporse of learning.
                </p>
            </div>
            <div class = "footer-content" style="padding-right:3rem;">
                <h3>Address:</h3>
                <p>Our Address<br> 
                     Abuja, Nigeria.
                </p>
                <h3>TelePhone:</h3>
                <a href="">08164696712</a>
                <h3>Contact Email</h3>
                <a href="">to_uremail@gmail.com</a> 
            </div>
            <div class = "footer-content last">
                <h3>category</h3>
                <a href="">Courses</a><br>
                <a href="">Exams</a>
            </div>
        </div>
        <h2>Built for the purpose of learning Using Django</h2>
        <a href="#">www.yourwebsite.com</a>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <script src="{% static 'js/javascript.js' %}"></script>
</body>

</html>

acetelapp/templates/acetelapp/login_courses.html
{% extends 'acetelapp/login_base.html' %}

{% load static %}

{% block content %}
<div class="browse section">
    <h2>Browse Courses</h2>
    <div class="browse-courses">
        {% for course in courses %}
        <a href="{% url 'acetelapp:registercourse' course_id=course.id %}" class="card-box">
            <div class="card">
                <img src="{{course.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-heading">{{course.title}}</h5>
                    <p class="card-text">{{course.description}}</p>
                    <p style="font-size: 0.9rem;">
                        <i class="far fa-clock" style="color:#055b38"></i> &nbsp;{{course.date}} <i
                            class="fas fa-user-friends" style="color:#055b38"></i>{{course.num_users_registered}}<span
                            style="float: right; font-size: 1.3rem; color:#055b38;">&#8358;{{course.amount}}</span>
                    </p>
                </div>
            </div>
        </a>
        {% endfor %}

    </div>

</div>

{% endblock %}

acetelapp/templates/acetelapp/login_page.html
    {% extends 'acetelapp/login_base.html' %}
    {% load static %}

    {% block content %}
    <div class="section about-section ">
        <div class="about-col-1">
            <h1>Welcome to OUR LEARNING platform</h1>
            <div>
                <h2>Access career-based, skills, and certificate programs
                    from OUR LEARNING platform to grow in your career.</h2>
            </div>
            <a href="#" class="get-started">Get Stated</a>
        </div>
        <div class="about-card">
            <div class="card card1">
                <p style="padding-top: 0.5rem; margin-bottom: 0;">Access the best anywhere and anytime</p>
                <div class="access-container">
                    <div class="access">
                        <i class="far fa-user" style="color:#055b38"></i>
                    </div>
                    <div class="access">
                        <i class="far fa-user" style="color:#055b38"></i>
                    </div>
                    <div class="access">
                        <span>+98</span>
                    </div>
                    
                </div>

            </div>
            <div class="about-container">
                <div class="about-img" style="background-image: url(/static/images/about-image.jpg);"></div>
            </div>

            <div class="card card2">
                <span class="cdspan"><i class="fas fa-book-open" style="color:#055b38"></i></span>
                <span>Compatible on all devices</span>
            </div>
        </div>
    </div>
    <div class="category section">
        <h2>Available Categories</h2>
        <div class="cate-section">
            <a href="#" class="courses">
                <img src = "{% static 'images/courses.JPG' %}" alt="">
                <li></li>
                <span><i class="fas fa-book-open"></i>&nbsp&nbspCourses</span>
            </a>
            <a href="#" class="courses">
                <img src = "{% static 'images/exam.JPG' %}" alt="">
                <li></li>
                <span><i class="fas fa-book-open"></i>&nbsp&nbspExam</span>

            </a>
        </div>
    </div>
    <div class="browse section">
        <h2>Browse Courses</h2>
        <div class="browse-courses">
            {% for course in courses %}
            <a href="{% url 'acetelapp:registercourse' course_id=course.id %}" class="card-box">
                <div class="card">
                    <img src ="{{course.image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-heading">{{course.title}}</h5>
                        <p class="card-text">{{course.description}}</p>
                        <p style="font-size: 0.9rem;">
                            <i class="far fa-clock" style="color:#055b38"></i> &nbsp;{{course.date}} <i
                                class="fas fa-user-friends" style="color:#055b38"></i> {{course.num_users_registered}} <span
                                style="float: right; font-size: 1.3rem; color:#055b38;">&#8358;{{course.amount}}</span>
                        </p>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
        <div class="viewall">
            <a href="{% url 'acetelapp:login_courses' %}" class="get-started btn">View All</a>
        </div>

    </div>
    <div class="section learning">
        <h2>Flexible learning</h2>
        <div class="learner-box">
            <div class="learner">
                <div class="learner-image" style="background-image: url(/static/images/learner-image.jpg);"></div>
            </div>
            <div class="learner-plan">
                <div>
                    <h1>Stay Ahead and Compete Globally</h1>
                </div>
                <div class="plan-list">
                    <li> <span><i class="fas fa-book-open" style="color:#055b38"></i></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Top Learning Contents thought by experts </li>
                    <li> <span><i class="fas fa-briefcase" style="color:#055b38"></i></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Learn at your own pace</li>
                    <li> <span><i class="far fa-clock" style="color:#055b38"></i></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ask questions while learning</li>
                    <li> <span><i class="fas fa-user-friends" style="color:#055b38"></i></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Inbuilt Test and exercises while learning</li>
                </div>
            </div>
        </div>
    </div>
    <div class="browse section explore">
        <h2>Explore Top Test/Exams</h2>
        <div class="browse-courses test-exam">
            {% for exam in exams %}
            <a href="{% url 'acetelapp:registerexam' exam_id=exam.id %}" class="card-box">
                <div class="card title-card">
                    <img src ="{{exam.image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-heading">{{exam.title}}</h5>
                        <p class="card-text">{{exam.description}}</p>
                    </div>
                    <div class="title">
                            <p style="font-size: 0.9rem;">
                                <i class="far fa-comment-alt"></i> &nbsp;{{exam.question}} Questions <span style="float:right"><i
                                    class="fas fa-user-friends"></i>&nbsp;227 Subscribers</span></p>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div> 
        <div class="viewall">
            <a href="{% url 'acetelapp:login_exams' %}" class="get-started btn">View All</a>
        </div>  
    </div>
    <div class="why-us section">
          <div><h2>Why Us?</h2></div>  
        <div class="why-us-section">
            <div class="why-us-box">
                <h2>
                    What you need to know as our Students
                </h2>
            </div>
            <div class="why-us-box">
                <span><img src = "{% static 'images/avatar.JPG' %}" alt="" 
                    style="border-radius: 50%; width: 3rem; 
                    height:3rem"> Quality Control </span>
                <p>
                    Each Learning Content is of top quality and have been 
                    reviewed by quality control experts.
                </p>
            </div>
            <div class="why-us-box">
                <span><img src = "{% static 'images/avatar.JPG' %}" alt=""
                     style="border-radius: 50%; width: 3rem;
                      height:3rem"> Modular Learning </span>
                <p>
                    Contents are broken down into small versions called
                     modules for easy learning experience and each module
                      have exercises for the students.
                </p>
            </div>
            <div class="why-us-box">
                <span><img src = "{% static 'images/avatar.JPG' %}" alt="" 
                    style="border-radius: 50%; width: 3rem; 
                    height:3rem"> Real Life Projects </span>
                <p>
                    Projects are assigned to students during 
                    and after learning to ascertained their 
                    level of understanding of the course before
                     certifications.
                </p>
            </div>

        </div>
        
    </div>
    <div class="learn-expert section">
        <div class="expert-box" style="width:100%">
            <div class="expert-img" style="width:35%">
                <img src = "{% static 'images/expert.JPG' %}" alt="" style="width:35%">
            </div>
    
            <div class="expert-text" style="width:60%">
                <h1>Learn with Experts</h1>
                <p>Learn from top creators ready to grow with you</p>
                <button><a href="#">Get Started</a></button>
            </div>
        </div>
    </div>
    {% endblock %} 

    